### ISSUE TITLE
NO LICENSE file !

### ISSUE THREAD

**Issue by CristinaCismas** [mohsen1/better-console#11]
Hi, we would like to use this in our project, but we need to be able to cite a license file. I noticed in the package.json that the license is BSD.  Any chance you could add a file explicitly stating it ? 
Thank you!

**Comment by mohsen1** [comment]
Hi, 

Yes it is BSD. I'll add a license file. A PR is also welcome

**Comment by mohsen1** [comment]
Fixed in 1.0.1
