### ISSUE TITLE
Issue with browserify and IE9

### ISSUE THREAD

**Issue by Asuza** [mohsen1/better-console#5]
This is kind of obscure, but I wanted to let you know about it regardless. I have a project in which I include your `better-console` module for much nicer debugging/output while I work on features in Node. When I convert my code to be used in the browser with [browserify](http://browserify.org/), IE9 breaks. If I remove `better-console` from my application and re-browserify it, everything works fine.

**Comment by mohsen1** [comment]
Maybe it's because of this line: https://github.com/mohsen1/better-console/blob/master/index.js#L15

Can you remove export from there and see if it helps?

**Comment by mohsen1** [comment]
Should be fixed in v1
